services:
  web:
    build: .
    command: rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
    environment:
      - REDIS_URL=redis://redis:6379/0

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ecommerce_api
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce_api_development
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

volumes:
  pgdata: